TicketMaster/Models/PAY_PAYMENT.cs
namespace TicketMaster.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class PAY_PAYMENT
    {
        [Key]
        [Column(Order = 0)]
        [StringLength(20)]
        public string TIC_ID { get; set; }

        [Key]
        [Column(Order = 1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int PAY_ID { get; set; }

        [Column(TypeName = "numeric")]
        public decimal PAY_TOTAL { get; set; }

        public DateTime PAY_PAYMENTDATE { get; set; }

        public int PAY_CANCELED { get; set; }

        public int CUR_ID { get; set; }

        [StringLength(100)]
        public string PAY_PINREFNUMBER { get; set; }

        public virtual PAY_TICKET PAY_TICKET { get; set; }
    }
}

TicketMaster/Models/PAY_TICKET.cs
namespace TicketMaster.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class PAY_TICKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAY_TICKET()
        {
            PAY_PAYMENT = new HashSet<PAY_PAYMENT>();
        }

        [Key]
        [StringLength(20)]
        public string TIC_ID { get; set; }

        public short BRA_ID { get; set; }

        public int? DLY_ID { get; set; }

        public int TIC_TICKETSTATE { get; set; }

        [Required]
        [StringLength(20)]
        public string CUS_ID { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? TIC_SUBTOTAL { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? TIC_TAX { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? TIC_TOTALAMOUNT { get; set; }

        [StringLength(20)]
        public string TIC_SELLER { get; set; }

        public int GEN_CUR_ID { get; set; }

        public short GEN_TAX_ID { get; set; }

        public int PUT_ID { get; set; }

        public int? EXC_ID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAY_PAYMENT> PAY_PAYMENT { get; set; }
    }
}

TicketMaster/Models/PaymentTicketViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TicketMaster.Models
{
    public class PaymentTicketViewModel
    {
        [Key]
        public string tic_id { get; set; }
        public string  cliente { get; set; }
        public decimal monto { get; set; }
        public decimal total_monto { get; set; }
        public decimal pago_pendiente { get; set; }
    }
}

TicketMaster/Models/ShopDb.cs
namespace TicketMaster.Models
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public class ShopDb : DbContext
    {
        public ShopDb()
            : base("name=ShopDbContext")
        {
        }

        public virtual DbSet<PAY_PAYMENT> PAY_PAYMENT { get; set; }
        public virtual DbSet<PAY_TICKET> PAY_TICKET { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PAY_PAYMENT>()
                .Property(e => e.PAY_TOTAL)
                .HasPrecision(12, 2);

            modelBuilder.Entity<PAY_TICKET>()
                .Property(e => e.TIC_SUBTOTAL)
                .HasPrecision(12, 4);

            modelBuilder.Entity<PAY_TICKET>()
                .Property(e => e.TIC_TAX)
                .HasPrecision(12, 4);

            modelBuilder.Entity<PAY_TICKET>()
                .Property(e => e.TIC_TOTALAMOUNT)
                .HasPrecision(12, 4);

            modelBuilder.Entity<PAY_TICKET>()
                .HasMany(e => e.PAY_PAYMENT)
                .WithRequired(e => e.PAY_TICKET)
                .WillCascadeOnDelete(false);
        }

        public System.Data.Entity.DbSet<TicketMaster.Models.PaymentTicketViewModel> PaymentTicketViewModels { get; set; }
    }
}

TicketMaster/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TicketMaster.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TicketMaster/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicketMaster.Models;

namespace TicketMaster.Controllers
{
    public class PaymentsController : Controller
    {
        private readonly ShopDb db = new ShopDb();

        public ActionResult Registrar()
        {
            ViewBag.TIC_ID = new SelectList(db.PAY_TICKET,"TIC_ID","TIC_ID");
            return View();
        }

        [HttpPost]
        public ActionResult Registrar(PAY_PAYMENT payment)
        {
            ViewBag.TIC_ID = new SelectList(db.PAY_TICKET, "TIC_ID", "TIC_ID");

            if (!ModelState.IsValid)
            {
                return View(payment);
            }

            payment.PAY_PAYMENTDATE = DateTime.Now;
            payment.PAY_CANCELED = 0;
            payment.CUR_ID = 1;

            db.PAY_PAYMENT.Add(payment);

            try
            {
                db.SaveChanges();
            }
            catch (Exception)
            {

                throw;
            }

            return RedirectToAction("Index","Tickets");
        }

        public ActionResult Delete(string id)
        {
            return View(db.PAY_TICKET.FirstOrDefault(x => x.TIC_ID == id));
        }
        
        [HttpPost]
        public ActionResult Delete(string tic_id,string id)
        {
            var pays = db.PAY_PAYMENT.Where(p => p.TIC_ID == tic_id).ToList();

            foreach(var pay in pays)
            {
                db.PAY_PAYMENT.Remove(pay);
            }

            try
            {

                db.SaveChanges();
            }
            catch (Exception)
            {
                throw;
            }

            return RedirectToAction("Index", "Tickets");
        }
    }
}

TicketMaster/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicketMaster.Models;

namespace TicketMaster.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ShopDb db = new ShopDb();
        public TicketsController()
        {

        }

        public ActionResult Index()
        {
            var tickets = db.Database.SqlQuery<PaymentTicketViewModel> ("select pt.tic_id, pt.cus_id as cliente, isnull(sum(pp.PAY_TOTAL),0) as Monto, pt.TIC_TOTALAMOUNT as total_monto,"
            +" pt.TIC_TOTALAMOUNT - isnull(sum(pp.PAY_TOTAL), 0) as pago_pendiente"
            +" from pay_ticket as pt left join pay_payment pp"
            +" on pt.tic_id = pp.tic_id"
            +" group by pt.tic_id, pt.cus_id, pt.TIC_TOTALAMOUNT");

            return View(tickets);
        }
    }
}

TicketMaster/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TicketMaster/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TicketMaster/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TicketMaster/Views/Payments/Delete.cshtml
@model TicketMaster.Models.PAY_TICKET

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PAY_TICKET</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BRA_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BRA_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DLY_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DLY_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TIC_TICKETSTATE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIC_TICKETSTATE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CUS_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CUS_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TIC_SUBTOTAL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIC_SUBTOTAL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TIC_TAX)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIC_TAX)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TIC_TOTALAMOUNT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIC_TOTALAMOUNT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TIC_SELLER)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIC_SELLER)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GEN_CUR_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GEN_CUR_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GEN_TAX_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GEN_TAX_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PUT_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PUT_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EXC_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EXC_ID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <input type="hidden" value="@Html.DisplayFor(model => model.TIC_ID)" name="tic_id" />

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TicketMaster/Views/Payments/Registrar.cshtml
@model TicketMaster.Models.PAY_PAYMENT

@{
    ViewBag.Title = "Registrar";
}

<h2>Registrar Pagos</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TIC_ID, "TIC_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TIC_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TIC_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PAY_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PAY_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PAY_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PAY_TOTAL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PAY_TOTAL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PAY_TOTAL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TicketMaster/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TicketMaster/Views/Tickets/Index.cshtml
@model IEnumerable<TicketMaster.Models.PaymentTicketViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.cliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.monto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.total_monto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.pago_pendiente)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.cliente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.monto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.total_monto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.pago_pendiente)
        </td>
        <td>
            @Html.ActionLink("Edit", "Payments", new { id=item.tic_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.tic_id }) |
            <a href="@Url.Action("Delete","Payments",new { id=item.tic_id })">Delete</a>
        </td>
    </tr>
}

</table>